### PR TITLE
Html validation

### PR DESCRIPTION
**Pull request by martinburchell**
I've fixed some HTML5 validation errors

With the itemprop and content attribute changes I wasn't totally sure what I was doing, other than getting the validator to pass!

### CODE REVIEW

**Comment by nickyoung87** [comment]
@martinburchell Thanks for fixing these. I am still looking at the schema ones more closely. I think there may actually be a bigger problem with them than just changing the attributes.

The first commit is ok so that one I am not worried about. 

Your second commit that changes the `<div>` to a `<span>` I think we should revert. This is because since the description can allow HTML someone may enter a block element which would not be allowed in the `<span>` tag.

And again, the 3rd and 4th commit I am going to need more time to look over.

**Comment by martinburchell** [comment]
@nickyoung87 Thanks for the comments. I've reverted the div/span commit. I realised my template could just be fixed.

**Comment by martinburchell** [comment]
@nickyoung87 just checking if you've had a chance to try this. I've upgraded to the latest stable release so I no longer get the errors about the spaces between attributes but still get the content and itemprop errors

**Comment by nickyoung87** [comment]
@martinburchell Sorry for the delay. There was a lot to look over in your PR :) Looks like it all checks out to me so I have merged it.

Thanks!

**Pull request merged**
