### PR TITLE
allow other plugins to add own event tags

### PR DESCRIPTION
**Pull request by Brummolix**
I have edited the original PR as discussed in https://github.com/moonstonemedia/Simple-Calendar/pull/142 and created this new one.

### CODE REVIEW

**Comment by pderksen** [comment]
@Brummolix Thanks for submitting another patch. This is still quite a structural change so we'll have to review in more depth at some point. Thanks for your patience.

**Comment by nickyoung87** [comment]
@Brummolix Could you share a gist of the code you are using to make your own event tag?

**Comment by Brummolix** [comment]
https://gist.github.com/anonymous/4f63132f5d50f2251a6add73b6ce37ba#file-simplecalendarcustomeventtag-php

**Comment by nickyoung87** [comment]
@Brummolix Thanks!

**Pull request merged**
