### PR TITLE
allow other plugins to add own event tags

### PR DESCRIPTION
**Pull request by Brummolix**

### CODE REVIEW

**Comment by nickyoung87** [comment]
Thanks for the PR. We will look at this when we get a chance.

**Comment by Brummolix** [comment]
I have change it a bit again to make it more flexible:
- provide $event to the shortcode plugin to have full flexibility
- add realUid (id from google) to have even more flexibility
(See 2 more commits for details)

**Comment by nickyoung87** [comment]
@Brummolix I have added your idea here of `realUid` but a bit differently. What I did was fix the normal `[id]` tag because that should have been returning just the event ID anyway. I then added a new tag callled `[ical-id]` for the iCal ID.

For the other part of your PR though I will have to investigate more. We discussed quite heavily if we should include filters for customizing event template codes but ultimately we agreed not to add them in. The main reason here would be performance. We didn't think that it was a good trade off to have to run that many extra calls through a filter for all of the events. Are you running the modified code you provided? If so, how is it performance wise and have you added any custom shortcodes through filters that way?

**Comment by Brummolix** [comment]
I'm running the code, but I never measured performance. For my site it is OK but it does not have so many page views at all.
The basic idea behind this was to have a normal blog post which is linked to an event. In the event a link to this blog post is added (if there is such a blogpost). Any idea how to reach this without custom event tags?

**Comment by nickyoung87** [comment]
Did you try the blog feed add-on and it didn't do quite what you were looking for?

https://wordpress.org/plugins/simple-calendar-blog-feed/

Maybe you have a URL example of how you have it setup now so that I can see better what you mean?

**Comment by Brummolix** [comment]
Maybe my description was not clear enough.
I use a Google calendar which is shown on the web page. Additionally I can save the event-id of an google event in a blog post. If this combination exists an additional link to the blog post is added to the event.

**Comment by nickyoung87** [comment]
Ok I think I understand. And the way the blog post is added to the event is by using the custom event template code you created with a filter correct?

**Comment by Brummolix** [comment]
Exactly.

**Comment by Brummolix** [comment]
I just merged back the current dev branch and removed my realUid, too.
So the change is now again very close to the current dev branch.

**Comment by nickyoung87** [comment]
@Brummolix Thanks for adding the new changes to get it closer to dev. Will get back to you as soon as I can on this.

**Comment by pderksen** [comment]
@Brummolix I took a look at this and I don't think it's going to work with our structure in it's current state. A couple things:

1) We would like to see private functions used within the `Event_Builder` class in this case most likely.

2) Our filters names follow the format `simcal_xxx` so something like this would make more sense for the filter hook names.

`simcal_event_tags`

Could you propose a revised PR and submit to the `custom-event-tags` branch?

Thanks again for proposing this update!

**Comment by Brummolix** [comment]
See https://github.com/moonstonemedia/Simple-Calendar/pull/211

**Pull request merged**
